package com.therighthon.cacophony;

import java.util.function.Supplier;

import net.dries007.tfc.config.BaseConfig;
import net.dries007.tfc.config.ConfigBuilder;

public class CacophonyClientConfig extends BaseConfig
{
    // General
    public final Supplier<Double> ambientSoundsScale;
    public final Supplier<Double> windSoundsScale;
    public final Supplier<Integer> dawnSoundRarity;
    public final Supplier<Integer> daySoundRarity;
    public final Supplier<Integer> duskSoundRarity;
    public final Supplier<Integer> darkSoundRarity;

    // Individual Species - Paste Spreadsheet Contents Here
    public final Supplier<Integer> birdRedwingedBlackbirdSoundRarity;
    public final Supplier<Integer> frogPacificTreeFrogSoundRarity;
    public final Supplier<Integer> frogSpadefootToadSoundRarity;
    public final Supplier<Integer> frogSaharaFrogSoundRarity;
    public final Supplier<Integer> frogStripedRocketFrogSoundRarity;
    public final Supplier<Integer> frogBrazilianTorrentFrogSoundRarity;
    public final Supplier<Integer> frogPurpleFrogSoundRarity;
    public final Supplier<Integer> frogMarshFrogSoundRarity;
    public final Supplier<Integer> frogBandedBullfrogSoundRarity;
    public final Supplier<Integer> frogCentralCoastStubfootToadSoundRarity;
    public final Supplier<Integer> frogNorthernCricketFrogSoundRarity;
    public final Supplier<Integer> frogAnkarafaSkeletonFrogSoundRarity;
    public final Supplier<Integer> frogPalauFrogSoundRarity;
    public final Supplier<Integer> frogEdibleFrogSoundRarity;
    public final Supplier<Integer> frogMotorbikeFrogSoundRarity;
    public final Supplier<Integer> frogEuropeanTreeFrogSoundRarity;
    public final Supplier<Integer> frogBorealDiggingFrogSoundRarity;
    public final Supplier<Integer> frogDybowskisFrogSoundRarity;
    public final Supplier<Integer> frogWoodFrogSoundRarity;
    public final Supplier<Integer> frogTalyshToadSoundRarity;
    public final Supplier<Integer> frogOliveToadSoundRarity;
    public final Supplier<Integer> frogCentralAsianToadSoundRarity;
    public final Supplier<Integer> frogSpectacledToadSoundRarity;
    public final Supplier<Integer> frogHainanToadSoundRarity;
    public final Supplier<Integer> frogTengchongLeafLitterToadSoundRarity;
    public final Supplier<Integer> frogPaintedChorusFrogSoundRarity;
    public final Supplier<Integer> frogDarkSpottedFrogSoundRarity;
    public final Supplier<Integer> frogFireBelliedToadSoundRarity;
    public final Supplier<Integer> frogCascadesFrogSoundRarity;
    public final Supplier<Integer> frogCaneToadSoundRarity;
    public final Supplier<Integer> birdStriolatedBuntingSoundRarity;
    public final Supplier<Integer> birdMarshWrenSoundRarity;
    public final Supplier<Integer> birdPallasGrasshopperWarblerSoundRarity;
    public final Supplier<Integer> birdCollaredKingfisherSoundRarity;
    public final Supplier<Integer> birdSpottedTowheeSoundRarity;
    public final Supplier<Integer> frogSpringPeeperSoundRarity;
    public final Supplier<Integer> frogBorealChorusFrogSoundRarity;
    public final Supplier<Integer> birdCanadaWarblerSoundRarity;
    public final Supplier<Integer> birdOrientalReedWarblerSoundRarity;
    public final Supplier<Integer> birdOrientalSkylarkSoundRarity;
    public final Supplier<Integer> birdDjaRiverScrubWarblerSoundRarity;
    public final Supplier<Integer> frogBandedBananaFrogSoundRarity;
    public final Supplier<Integer> birdLouisianaWaterthrushSoundRarity;
    public final Supplier<Integer> birdScrubBlackbirdSoundRarity;
    public final Supplier<Integer> birdNorthernWaterthrushSoundRarity;
    public final Supplier<Integer> birdWesternMeadowlarkSoundRarity;
    public final Supplier<Integer> frogTwoColoredOvalFrogSoundRarity;
    public final Supplier<Integer> cricketSlenderHeathKatydidSoundRarity;
    public final Supplier<Integer> cricketMediterraneanKatydidSoundRarity;
    public final Supplier<Integer> cricketBlackLeggedMeadowKatydidSoundRarity;
    public final Supplier<Integer> cricketSpottedMeadowKatydidSoundRarity;
    public final Supplier<Integer> cricketEurasianMeadowKatydidSoundRarity;
    public final Supplier<Integer> cricketStraightLancedKatydidSoundRarity;
    public final Supplier<Integer> cricketAfricanMeadowKatydidSoundRarity;
    public final Supplier<Integer> cricketDrummingKatydidSoundRarity;
    public final Supplier<Integer> cricketBroadWingedBushKatydidSoundRarity;
    public final Supplier<Integer> cricketCaribbeanMeadowKatydidSoundRarity;
    public final Supplier<Integer> cricketLeafLadybirdCricketSoundRarity;
    public final Supplier<Integer> cricketTwoSpottedClicketSoundRarity;
    public final Supplier<Integer> cricketSteppeCricketSoundRarity;
    public final Supplier<Integer> cricketMongolianCricketSoundRarity;
    public final Supplier<Integer> cricketCommonGreenGrasshopperSoundRarity;
    public final Supplier<Integer> cricketIndomalayanFieldCricketSoundRarity;
    public final Supplier<Integer> cricketSumatranBrownCricketSoundRarity;
    public final Supplier<Integer> cricketFieldCricketSoundRarity;
    public final Supplier<Integer> cricketOceanicFieldCricketSoundRarity;
    public final Supplier<Integer> cricketBrownSpottedBushCricketSoundRarity;
    public final Supplier<Integer> birdBronzySunbirdSoundRarity;
    public final Supplier<Integer> birdStreakySeedeaterSoundRarity;
    public final Supplier<Integer> birdGracefulPriniaSoundRarity;
    public final Supplier<Integer> birdGreaterWhitethroatSoundRarity;
    public final Supplier<Integer> birdCommonMynaSoundRarity;
    public final Supplier<Integer> birdAsianDesertWarblerSoundRarity;
    public final Supplier<Integer> birdWhiteWingedSnowfinchSoundRarity;
    public final Supplier<Integer> birdAsianShortToedLarkSoundRarity;
    public final Supplier<Integer> birdPeruvianMeadowlarkSoundRarity;
    public final Supplier<Integer> birdMeadowBuntingSoundRarity;
    public final Supplier<Integer> birdLongTailedMeadowlarkSoundRarity;
    public final Supplier<Integer> birdPatagonianSierraFinchSoundRarity;
    public final Supplier<Integer> birdNorthernCarmineBeeEaterSoundRarity;
    public final Supplier<Integer> birdAfricanParadiseFlycatcherSoundRarity;
    public final Supplier<Integer> birdEasternMeadowlarkSoundRarity;
    public final Supplier<Integer> birdBarnSwallowSoundRarity;
    public final Supplier<Integer> birdYellowHeadedBlackbirdSoundRarity;
    public final Supplier<Integer> birdSongSparrowSoundRarity;
    public final Supplier<Integer> birdRufousCollaredSparrowSoundRarity;
    public final Supplier<Integer> birdCommonStarlingSoundRarity;
    public final Supplier<Integer> birdSnowBuntingSoundRarity;
    public final Supplier<Integer> birdRavenSoundRarity;
    public final Supplier<Integer> birdResplendentQuetzalSoundRarity;
    public final Supplier<Integer> frogRainforestRocketFrogSoundRarity;
    public final Supplier<Integer> frogStrawberryPoisonFrogSoundRarity;
    public final Supplier<Integer> frogHimalayaFoamNestFrogSoundRarity;
    public final Supplier<Integer> birdWhiteCheekedBarbetSoundRarity;
    public final Supplier<Integer> frogMalabarGlidingFrogSoundRarity;
    public final Supplier<Integer> frogStumpffiaMegsoniSoundRarity;
    public final Supplier<Integer> frogCopesGrayTreeFrogSoundRarity;
    public final Supplier<Integer> frogBrilliantThighedPoisonFrogSoundRarity;
    public final Supplier<Integer> frogStephensRocketFrogSoundRarity;
    public final Supplier<Integer> frogHoltsRobberFrogSoundRarity;
    public final Supplier<Integer> frogAmazonToadSoundRarity;
    public final Supplier<Integer> frogPebasStubfootToadSoundRarity;
    public final Supplier<Integer> frogGranularToadSoundRarity;
    public final Supplier<Integer> frogBlacksmithFrogSoundRarity;
    public final Supplier<Integer> birdGreatKiskadeeSoundRarity;
    public final Supplier<Integer> birdThrushNightingaleSoundRarity;
    public final Supplier<Integer> birdBlackCappedChickadeeSoundRarity;
    public final Supplier<Integer> birdMourningDoveSoundRarity;
    public final Supplier<Integer> birdEurasianEagleOwlSoundRarity;
    public final Supplier<Integer> birdTawnyOwlSoundRarity;
    public final Supplier<Integer> birdLongEaredOwlSoundRarity;
    public final Supplier<Integer> birdSnowyOwlSoundRarity;
    public final Supplier<Integer> birdCommonCuckooSoundRarity;
    public final Supplier<Integer> birdBlackAndWhiteCasquedHornbillSoundRarity;
    public final Supplier<Integer> birdGreenBackedCamaropteraSoundRarity;
    public final Supplier<Integer> birdSpottedDoveSoundRarity;
    public final Supplier<Integer> birdOrientalBayOwlSoundRarity;
    public final Supplier<Integer> birdCoppersmithBarbetSoundRarity;
    public final Supplier<Integer> birdLargeFrogmouthSoundRarity;
    public final Supplier<Integer> birdBoldStripedTitBabblerSoundRarity;
    public final Supplier<Integer> birdBlueEaredBarbetSoundRarity;
    public final Supplier<Integer> birdRufousTailedTailorbirdSoundRarity;
    public final Supplier<Integer> birdYellowVentedBulbulSoundRarity;
    public final Supplier<Integer> birdPlaintiveCuckooSoundRarity;
    public final Supplier<Integer> birdWilsonsBirdOfParadiseSoundRarity;
    public final Supplier<Integer> birdPalmCockatooSoundRarity;
    public final Supplier<Integer> birdBlueWingedKookaburraSoundRarity;
    public final Supplier<Integer> birdSuperbPittaSoundRarity;
    public final Supplier<Integer> birdPapuanKingParrotSoundRarity;
    public final Supplier<Integer> birdMagnificentBirdOfParadiseSoundRarity;
    public final Supplier<Integer> birdSulphurCrestedCockatooSoundRarity;
    public final Supplier<Integer> birdPacificWrenSoundRarity;
    public final Supplier<Integer> birdAmericanRobinSoundRarity;
    public final Supplier<Integer> birdBarredOwlSoundRarity;
    public final Supplier<Integer> birdDarkEyedJunkoSoundRarity;
    public final Supplier<Integer> birdGreatHornedOwlSoundRarity;
    public final Supplier<Integer> birdRaggianaBirdOfParadiseSoundRarity;
    public final Supplier<Integer> birdTropicalMockingbirdSoundRarity;
    public final Supplier<Integer> birdLewisWoodpeckerSoundRarity;
    public final Supplier<Integer> birdYellowBackedOrioleSoundRarity;
    public final Supplier<Integer> birdKeelBilledToucanSoundRarity;
    public final Supplier<Integer> birdYellowThroatedToucanSoundRarity;
    public final Supplier<Integer> birdCrimsonBackedTanagerSoundRarity;
    public final Supplier<Integer> birdSlateColoredGrosbeakSoundRarity;
    public final Supplier<Integer> birdSpectacledOwlSoundRarity;
    public final Supplier<Integer> birdCollaredTrogonSoundRarity;
    public final Supplier<Integer> birdPaleBreastedThrushSoundRarity;
    public final Supplier<Integer> birdMountainWrenSoundRarity;
    public final Supplier<Integer> birdGreatAntshrikeSoundRarity;
    public final Supplier<Integer> birdRedLoredAmazonSoundRarity;
    public final Supplier<Integer> birdMontezumaOropendolaSoundRarity;
    public final Supplier<Integer> birdNorthernCardinalSoundRarity;
    public final Supplier<Integer> birdEasternWoodPeweeSoundRarity;
    public final Supplier<Integer> birdWoodThrushSoundRarity;
    public final Supplier<Integer> birdAmericanGoldfinchSoundRarity;
    public final Supplier<Integer> birdFoxSparrowSoundRarity;
    public final Supplier<Integer> birdGreatTitSoundRarity;
    public final Supplier<Integer> frogMeditteraneanTreeFrogSoundRarity;
    public final Supplier<Integer> birdTwoBarredCrossbillSoundRarity;
    public final Supplier<Integer> birdVariedThrushSoundRarity;
    public final Supplier<Integer> frogChineseTreeFrogSoundRarity;
    public final Supplier<Integer> frogMoltrechtsGreenTreeFrogSoundRarity;
    public final Supplier<Integer> birdBrownBulbulSoundRarity;
    public final Supplier<Integer> birdJapaneseBushWarblerSoundRarity;
    public final Supplier<Integer> birdAzureWingedMagpieSoundRarity;
    public final Supplier<Integer> birdTaiwanBarbetSoundRarity;
    public final Supplier<Integer> birdAsianKoelSoundRarity;
    public final Supplier<Integer> birdBeijingBabblerSoundRarity;
    public final Supplier<Integer> birdWhistlingCisticolaSoundRarity;
    public final Supplier<Integer> birdChalkBrowedMockingbirdSoundRarity;
    public final Supplier<Integer> birdLaughingKookaburraSoundRarity;
    public final Supplier<Integer> birdWesternNicatorSoundRarity;
    public final Supplier<Integer> birdYellowBilledTuracoSoundRarity;
    public final Supplier<Integer> birdTambourineDoveSoundRarity;
    public final Supplier<Integer> birdSuperbLyrebirdSoundRarity;
    public final Supplier<Integer> birdWillieWagtailSoundRarity;
    public final Supplier<Integer> birdGreenImperialPigeonSoundRarity;
    public final Supplier<Integer> birdGlaucousWingedGullSoundRarity;
    public final Supplier<Integer> birdPigeoinGuillemotSoundRarity;
    public final Supplier<Integer> birdBonapartesGullSoundRarity;
    public final Supplier<Integer> birdCommonLoonSoundRarity;
    public final Supplier<Integer> birdBlackOystercatcherSoundRarity;
    public final Supplier<Integer> birdSemipalmatedPloverSoundRarity;
    public final Supplier<Integer> birdShortTailedShearwaterSoundRarity;
    public final Supplier<Integer> birdSlatyBackedGullSoundRarity;
    public final Supplier<Integer> birdNorthernFulmarSoundRarity;
    public final Supplier<Integer> birdForkTailedStormPetrelSoundRarity;
    public final Supplier<Integer> birdLaysanAlbatrossSoundRarity;
    public final Supplier<Integer> birdBlackTailedGullSoundRarity;
    public final Supplier<Integer> birdPomarineJaegerSoundRarity;
    public final Supplier<Integer> birdHarlequinDuckSoundRarity;
    public final Supplier<Integer> birdGreyTailedTattlerSoundRarity;
    public final Supplier<Integer> birdWhiteTailedTropicbirdSoundRarity;
    public final Supplier<Integer> birdRedFootedBoobySoundRarity;
    public final Supplier<Integer> birdWedgeTailedShearwaterSoundRarity;
    public final Supplier<Integer> birdGreatFrigatebirdSoundRarity;
    public final Supplier<Integer> birdWesternOspreySoundRarity;
    public final Supplier<Integer> birdGreatBlackBackedGullSoundRarity;
    public final Supplier<Integer> birdBlackBilledKittiwakeSoundRarity;
    public final Supplier<Integer> birdYellowLeggedGullSoundRarity;



    CacophonyClientConfig(ConfigBuilder builder)
    {
        builder.push("general");

        ambientSoundsScale = builder.comment("Scale all sounds in Cacophony, without affecting ambient sounds added by Vanilla or other mods").define("ambientSoundsScale", 1.0, 0.0, 1.0);
        windSoundsScale = builder.comment("Scale wind sounds in Cacophony, without affecting other ambient sounds").define("windSoundsScale", 1.0, 0.0, 1.0);
        dawnSoundRarity = builder.comment("Rarity modifier for sounds at dawn. 1/n chance of playing. 0 to disable sounds at this time.").define("dawnSoundRarity", 6, 0, 100);
        daySoundRarity = builder.comment("Rarity modifier for sounds during the day. 1/n chance of playing. 0 to disable sounds at this time.").define("dawnSoundRarity", 8, 0, 100);
        duskSoundRarity = builder.comment("Rarity modifier for sounds at dusk. 1/n chance of playing. 0 to disable sounds at this time.").define("dawnSoundRarity", 5, 0, 100);
        darkSoundRarity = builder.comment("Rarity modifier for sounds during the night. 1/n chance of playing. 0 to disable sounds at this time.").define("dawnSoundRarity", 12, 0, 100);

        builder.swap("individual");

        // Paste Spreadsheet Contents Here:
        birdRedwingedBlackbirdSoundRarity = builder.comment("Rarity modifier for calls of the Redwinged Blackbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdRedwingedBlackbirdSoundRarity", 6, 2, 100);
        frogPacificTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Pacific Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogPacificTreeFrogSoundRarity", 2, 2, 100);
        frogSpadefootToadSoundRarity = builder.comment("Rarity modifier for calls of the Spadefoot Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogSpadefootToadSoundRarity", 2, 2, 100);
        frogSaharaFrogSoundRarity = builder.comment("Rarity modifier for calls of the Sahara Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogSaharaFrogSoundRarity", 1, 2, 100);
        frogStripedRocketFrogSoundRarity = builder.comment("Rarity modifier for calls of the Striped Rocket Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogStripedRocketFrogSoundRarity", 1, 2, 100);
        frogBrazilianTorrentFrogSoundRarity = builder.comment("Rarity modifier for calls of the Brazilian Torrent Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBrazilianTorrentFrogSoundRarity", 1, 2, 100);
        frogPurpleFrogSoundRarity = builder.comment("Rarity modifier for calls of the Purple Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogPurpleFrogSoundRarity", 2, 2, 100);
        frogMarshFrogSoundRarity = builder.comment("Rarity modifier for calls of the Marsh Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogMarshFrogSoundRarity", 1, 2, 100);
        frogBandedBullfrogSoundRarity = builder.comment("Rarity modifier for calls of the Banded Bullfrog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBandedBullfrogSoundRarity", 1, 2, 100);
        frogCentralCoastStubfootToadSoundRarity = builder.comment("Rarity modifier for calls of the Central Coast Stubfoot Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogCentralCoastStubfootToadSoundRarity", 2, 2, 100);
        frogNorthernCricketFrogSoundRarity = builder.comment("Rarity modifier for calls of the Northern Cricket Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogNorthernCricketFrogSoundRarity", 2, 2, 100);
        frogAnkarafaSkeletonFrogSoundRarity = builder.comment("Rarity modifier for calls of the Ankarafa Skeleton Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogAnkarafaSkeletonFrogSoundRarity", 1, 2, 100);
        frogPalauFrogSoundRarity = builder.comment("Rarity modifier for calls of the Palau Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogPalauFrogSoundRarity", 1, 2, 100);
        frogEdibleFrogSoundRarity = builder.comment("Rarity modifier for calls of the Edible Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogEdibleFrogSoundRarity", 1, 2, 100);
        frogMotorbikeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Motorbike Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogMotorbikeFrogSoundRarity", 1, 2, 100);
        frogEuropeanTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the European Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogEuropeanTreeFrogSoundRarity", 1, 2, 100);
        frogBorealDiggingFrogSoundRarity = builder.comment("Rarity modifier for calls of the Boreal Digging Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBorealDiggingFrogSoundRarity", 1, 2, 100);
        frogDybowskisFrogSoundRarity = builder.comment("Rarity modifier for calls of the Dybowskis Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogDybowskisFrogSoundRarity", 1, 2, 100);
        frogWoodFrogSoundRarity = builder.comment("Rarity modifier for calls of the Wood Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogWoodFrogSoundRarity", 1, 2, 100);
        frogTalyshToadSoundRarity = builder.comment("Rarity modifier for calls of the Talysh Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogTalyshToadSoundRarity", 1, 2, 100);
        frogOliveToadSoundRarity = builder.comment("Rarity modifier for calls of the Olive Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogOliveToadSoundRarity", 1, 2, 100);
        frogCentralAsianToadSoundRarity = builder.comment("Rarity modifier for calls of the Central asian toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogCentralAsianToadSoundRarity", 1, 2, 100);
        frogSpectacledToadSoundRarity = builder.comment("Rarity modifier for calls of the Spectacled Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogSpectacledToadSoundRarity", 1, 2, 100);
        frogHainanToadSoundRarity = builder.comment("Rarity modifier for calls of the Hainan Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogHainanToadSoundRarity", 1, 2, 100);
        frogTengchongLeafLitterToadSoundRarity = builder.comment("Rarity modifier for calls of the Tengchong Leaf Litter Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogTengchongLeafLitterToadSoundRarity", 1, 2, 100);
        frogPaintedChorusFrogSoundRarity = builder.comment("Rarity modifier for calls of the Painted Chorus Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogPaintedChorusFrogSoundRarity", 1, 2, 100);
        frogDarkSpottedFrogSoundRarity = builder.comment("Rarity modifier for calls of the Dark Spotted Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogDarkSpottedFrogSoundRarity", 1, 2, 100);
        frogFireBelliedToadSoundRarity = builder.comment("Rarity modifier for calls of the Fire Bellied Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogFireBelliedToadSoundRarity", 1, 2, 100);
        frogCascadesFrogSoundRarity = builder.comment("Rarity modifier for calls of the Cascades Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogCascadesFrogSoundRarity", 1, 2, 100);
        frogCaneToadSoundRarity = builder.comment("Rarity modifier for calls of the Cane Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogCaneToadSoundRarity", 1, 2, 100);
        birdStriolatedBuntingSoundRarity = builder.comment("Rarity modifier for calls of the Striolated Bunting. 1/n chance of playing. 0 to disable this bird's calls").define("birdStriolatedBuntingSoundRarity", 5, 2, 100);
        birdMarshWrenSoundRarity = builder.comment("Rarity modifier for calls of the Marsh Wren. 1/n chance of playing. 0 to disable this bird's calls").define("birdMarshWrenSoundRarity", 5, 2, 100);
        birdPallasGrasshopperWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Pallas Grasshopper Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdPallasGrasshopperWarblerSoundRarity", 5, 2, 100);
        birdCollaredKingfisherSoundRarity = builder.comment("Rarity modifier for calls of the Collared Kingfisher. 1/n chance of playing. 0 to disable this bird's calls").define("birdCollaredKingfisherSoundRarity", 5, 2, 100);
        birdSpottedTowheeSoundRarity = builder.comment("Rarity modifier for calls of the Spotted Towhee. 1/n chance of playing. 0 to disable this bird's calls").define("birdSpottedTowheeSoundRarity", 5, 2, 100);
        frogSpringPeeperSoundRarity = builder.comment("Rarity modifier for calls of the Spring Peeper. 1/n chance of playing. 0 to disable this frog's calls").define("frogSpringPeeperSoundRarity", 3, 2, 100);
        frogBorealChorusFrogSoundRarity = builder.comment("Rarity modifier for calls of the Boreal Chorus Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBorealChorusFrogSoundRarity", 5, 2, 100);
        birdCanadaWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Canada Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdCanadaWarblerSoundRarity", 5, 2, 100);
        birdOrientalReedWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Oriental Reed Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdOrientalReedWarblerSoundRarity", 5, 2, 100);
        birdOrientalSkylarkSoundRarity = builder.comment("Rarity modifier for calls of the Oriental Skylark. 1/n chance of playing. 0 to disable this bird's calls").define("birdOrientalSkylarkSoundRarity", 5, 2, 100);
        birdDjaRiverScrubWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Dja River Scrub Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdDjaRiverScrubWarblerSoundRarity", 5, 2, 100);
        frogBandedBananaFrogSoundRarity = builder.comment("Rarity modifier for calls of the Banded Banana Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBandedBananaFrogSoundRarity", 5, 2, 100);
        birdLouisianaWaterthrushSoundRarity = builder.comment("Rarity modifier for calls of the Louisiana Waterthrush. 1/n chance of playing. 0 to disable this bird's calls").define("birdLouisianaWaterthrushSoundRarity", 5, 2, 100);
        birdScrubBlackbirdSoundRarity = builder.comment("Rarity modifier for calls of the Scrub Blackbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdScrubBlackbirdSoundRarity", 5, 2, 100);
        birdNorthernWaterthrushSoundRarity = builder.comment("Rarity modifier for calls of the Northern Waterthrush. 1/n chance of playing. 0 to disable this bird's calls").define("birdNorthernWaterthrushSoundRarity", 5, 2, 100); birdWesternMeadowlarkSoundRarity = builder.comment("Rarity modifier for calls of the Western Meadowlark. 1/n chance of playing. 0 to disable this bird's calls").define("birdWesternMeadowlarkSoundRarity", 9, 2, 100);
        frogTwoColoredOvalFrogSoundRarity = builder.comment("Rarity modifier for calls of the Two Colored Oval Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogTwoColoredOvalFrogSoundRarity", 1, 2, 100);
        cricketSlenderHeathKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Slender Heath Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketSlenderHeathKatydidSoundRarity", 3, 2, 100);
        cricketMediterraneanKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Mediterranean Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketMediterraneanKatydidSoundRarity", 3, 2, 100);
        cricketBlackLeggedMeadowKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Black Legged Meadow Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketBlackLeggedMeadowKatydidSoundRarity", 3, 2, 100);
        cricketSpottedMeadowKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Spotted Meadow Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketSpottedMeadowKatydidSoundRarity", 3, 2, 100);
        cricketEurasianMeadowKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Eurasian Meadow Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketEurasianMeadowKatydidSoundRarity", 3, 2, 100);
        cricketStraightLancedKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Straight Lanced Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketStraightLancedKatydidSoundRarity", 3, 2, 100);
        cricketAfricanMeadowKatydidSoundRarity = builder.comment("Rarity modifier for calls of the African Meadow Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketAfricanMeadowKatydidSoundRarity", 3, 2, 100);
        cricketDrummingKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Drumming Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketDrummingKatydidSoundRarity", 1, 2, 100);
        cricketBroadWingedBushKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Broad Winged Bush Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketBroadWingedBushKatydidSoundRarity", 3, 2, 100);
        cricketCaribbeanMeadowKatydidSoundRarity = builder.comment("Rarity modifier for calls of the Caribbean Meadow Katydid. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketCaribbeanMeadowKatydidSoundRarity", 4, 2, 100);
        cricketLeafLadybirdCricketSoundRarity = builder.comment("Rarity modifier for calls of the Leaf Ladybird Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketLeafLadybirdCricketSoundRarity", 3, 2, 100);
        cricketTwoSpottedClicketSoundRarity = builder.comment("Rarity modifier for calls of the Two Spotted Clicket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketTwoSpottedClicketSoundRarity", 3, 2, 100);
        cricketSteppeCricketSoundRarity = builder.comment("Rarity modifier for calls of the Steppe Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketSteppeCricketSoundRarity", 3, 2, 100);
        cricketMongolianCricketSoundRarity = builder.comment("Rarity modifier for calls of the Mongolian Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketMongolianCricketSoundRarity", 3, 2, 100);
        cricketCommonGreenGrasshopperSoundRarity = builder.comment("Rarity modifier for calls of the Common Green Grasshopper. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketCommonGreenGrasshopperSoundRarity", 3, 2, 100);
        cricketIndomalayanFieldCricketSoundRarity = builder.comment("Rarity modifier for calls of the Indomalayan Field Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketIndomalayanFieldCricketSoundRarity", 3, 2, 100);
        cricketSumatranBrownCricketSoundRarity = builder.comment("Rarity modifier for calls of the Sumatran Brown Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketSumatranBrownCricketSoundRarity", 3, 2, 100);
        cricketFieldCricketSoundRarity = builder.comment("Rarity modifier for calls of the Field Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketFieldCricketSoundRarity", 3, 2, 100);
        cricketOceanicFieldCricketSoundRarity = builder.comment("Rarity modifier for calls of the Oceanic Field Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketOceanicFieldCricketSoundRarity", 3, 2, 100);
        cricketBrownSpottedBushCricketSoundRarity = builder.comment("Rarity modifier for calls of the Brown Spotted Bush Cricket. 1/n chance of playing. 0 to disable this cricket's calls").define("cricketBrownSpottedBushCricketSoundRarity", 3, 2, 100);
        birdBronzySunbirdSoundRarity = builder.comment("Rarity modifier for calls of the Bronzy Sunbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdBronzySunbirdSoundRarity", 5, 2, 100);
        birdStreakySeedeaterSoundRarity = builder.comment("Rarity modifier for calls of the Streaky seedeater. 1/n chance of playing. 0 to disable this bird's calls").define("birdStreakySeedeaterSoundRarity", 5, 2, 100);
        birdGracefulPriniaSoundRarity = builder.comment("Rarity modifier for calls of the Graceful Prinia. 1/n chance of playing. 0 to disable this bird's calls").define("birdGracefulPriniaSoundRarity", 5, 2, 100);
        birdGreaterWhitethroatSoundRarity = builder.comment("Rarity modifier for calls of the Greater Whitethroat. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreaterWhitethroatSoundRarity", 5, 2, 100);
        birdCommonMynaSoundRarity = builder.comment("Rarity modifier for calls of the Common Myna. 1/n chance of playing. 0 to disable this bird's calls").define("birdCommonMynaSoundRarity", 5, 2, 100);
        birdAsianDesertWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Asian Desert Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdAsianDesertWarblerSoundRarity", 5, 2, 100);
        birdWhiteWingedSnowfinchSoundRarity = builder.comment("Rarity modifier for calls of the White Winged Snowfinch. 1/n chance of playing. 0 to disable this bird's calls").define("birdWhiteWingedSnowfinchSoundRarity", 5, 2, 100);
        birdAsianShortToedLarkSoundRarity = builder.comment("Rarity modifier for calls of the Asian Short Toed Lark. 1/n chance of playing. 0 to disable this bird's calls").define("birdAsianShortToedLarkSoundRarity", 5, 2, 100);
        birdPeruvianMeadowlarkSoundRarity = builder.comment("Rarity modifier for calls of the Peruvian Meadowlark. 1/n chance of playing. 0 to disable this bird's calls").define("birdPeruvianMeadowlarkSoundRarity", 5, 2, 100);
        birdMeadowBuntingSoundRarity = builder.comment("Rarity modifier for calls of the Meadow Bunting. 1/n chance of playing. 0 to disable this bird's calls").define("birdMeadowBuntingSoundRarity", 5, 2, 100);
        birdLongTailedMeadowlarkSoundRarity = builder.comment("Rarity modifier for calls of the Long Tailed Meadowlark. 1/n chance of playing. 0 to disable this bird's calls").define("birdLongTailedMeadowlarkSoundRarity", 5, 2, 100);
        birdPatagonianSierraFinchSoundRarity = builder.comment("Rarity modifier for calls of the Patagonian Sierra Finch. 1/n chance of playing. 0 to disable this bird's calls").define("birdPatagonianSierraFinchSoundRarity", 5, 2, 100);
        birdNorthernCarmineBeeEaterSoundRarity = builder.comment("Rarity modifier for calls of the Northern Carmine Bee Eater. 1/n chance of playing. 0 to disable this bird's calls").define("birdNorthernCarmineBeeEaterSoundRarity", 5, 2, 100);
        birdAfricanParadiseFlycatcherSoundRarity = builder.comment("Rarity modifier for calls of the African Paradise Flycatcher. 1/n chance of playing. 0 to disable this bird's calls").define("birdAfricanParadiseFlycatcherSoundRarity", 5, 2, 100);
        birdEasternMeadowlarkSoundRarity = builder.comment("Rarity modifier for calls of the Eastern Meadowlark. 1/n chance of playing. 0 to disable this bird's calls").define("birdEasternMeadowlarkSoundRarity", 5, 2, 100);
        birdBarnSwallowSoundRarity = builder.comment("Rarity modifier for calls of the Barn Swallow. 1/n chance of playing. 0 to disable this bird's calls").define("birdBarnSwallowSoundRarity", 5, 2, 100);
        birdYellowHeadedBlackbirdSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Headed Blackbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowHeadedBlackbirdSoundRarity", 5, 2, 100);
        birdSongSparrowSoundRarity = builder.comment("Rarity modifier for calls of the Song Sparrow. 1/n chance of playing. 0 to disable this bird's calls").define("birdSongSparrowSoundRarity", 5, 2, 100);
        birdRufousCollaredSparrowSoundRarity = builder.comment("Rarity modifier for calls of the Rufous Collared Sparrow. 1/n chance of playing. 0 to disable this bird's calls").define("birdRufousCollaredSparrowSoundRarity", 5, 2, 100);
        birdCommonStarlingSoundRarity = builder.comment("Rarity modifier for calls of the Common Starling. 1/n chance of playing. 0 to disable this bird's calls").define("birdCommonStarlingSoundRarity", 5, 2, 100);
        birdSnowBuntingSoundRarity = builder.comment("Rarity modifier for calls of the Snow Bunting. 1/n chance of playing. 0 to disable this bird's calls").define("birdSnowBuntingSoundRarity", 5, 2, 100); birdRavenSoundRarity = builder.comment("Rarity modifier for calls of the Raven. 1/n chance of playing. 0 to disable this bird's calls").define("birdRavenSoundRarity", 5, 2, 100);
        birdResplendentQuetzalSoundRarity = builder.comment("Rarity modifier for calls of the Resplendent Quetzal. 1/n chance of playing. 0 to disable this bird's calls").define("birdResplendentQuetzalSoundRarity", 5, 2, 100);
        frogRainforestRocketFrogSoundRarity = builder.comment("Rarity modifier for calls of the Rainforest Rocket Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogRainforestRocketFrogSoundRarity", 1, 2, 100);
        frogStrawberryPoisonFrogSoundRarity = builder.comment("Rarity modifier for calls of the Strawberry Poison Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogStrawberryPoisonFrogSoundRarity", 1, 2, 100);
        frogHimalayaFoamNestFrogSoundRarity = builder.comment("Rarity modifier for calls of the Himalaya foam nest frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogHimalayaFoamNestFrogSoundRarity", 1, 2, 100);
        birdWhiteCheekedBarbetSoundRarity = builder.comment("Rarity modifier for calls of the White Cheeked Barbet. 1/n chance of playing. 0 to disable this bird's calls").define("birdWhiteCheekedBarbetSoundRarity", 5, 2, 100);
        frogMalabarGlidingFrogSoundRarity = builder.comment("Rarity modifier for calls of the Malabar Gliding Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogMalabarGlidingFrogSoundRarity", 2, 2, 100);
        frogStumpffiaMegsoniSoundRarity = builder.comment("Rarity modifier for calls of the Stumpffia megsoni. 1/n chance of playing. 0 to disable this frog's calls").define("frogStumpffiaMegsoniSoundRarity", 1, 2, 100);
        frogCopesGrayTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Copes Gray Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogCopesGrayTreeFrogSoundRarity", 1, 2, 100);
        frogBrilliantThighedPoisonFrogSoundRarity = builder.comment("Rarity modifier for calls of the Brilliant Thighed Poison Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBrilliantThighedPoisonFrogSoundRarity", 1, 2, 100);
        frogStephensRocketFrogSoundRarity = builder.comment("Rarity modifier for calls of the Stephens Rocket Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogStephensRocketFrogSoundRarity", 1, 2, 100);
        frogHoltsRobberFrogSoundRarity = builder.comment("Rarity modifier for calls of the Holts Robber Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogHoltsRobberFrogSoundRarity", 1, 2, 100);
        frogAmazonToadSoundRarity = builder.comment("Rarity modifier for calls of the Amazon Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogAmazonToadSoundRarity", 1, 2, 100);
        frogPebasStubfootToadSoundRarity = builder.comment("Rarity modifier for calls of the Pebas Stubfoot Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogPebasStubfootToadSoundRarity", 1, 2, 100);
        frogGranularToadSoundRarity = builder.comment("Rarity modifier for calls of the Granular Toad. 1/n chance of playing. 0 to disable this frog's calls").define("frogGranularToadSoundRarity", 1, 2, 100);
        frogBlacksmithFrogSoundRarity = builder.comment("Rarity modifier for calls of the Blacksmith Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogBlacksmithFrogSoundRarity", 1, 2, 100);
        birdGreatKiskadeeSoundRarity = builder.comment("Rarity modifier for calls of the Great Kiskadee. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatKiskadeeSoundRarity", 5, 2, 100);
        birdThrushNightingaleSoundRarity = builder.comment("Rarity modifier for calls of the Thrush Nightingale. 1/n chance of playing. 0 to disable this bird's calls").define("birdThrushNightingaleSoundRarity", 5, 2, 100);
        birdBlackCappedChickadeeSoundRarity = builder.comment("Rarity modifier for calls of the Black Capped Chickadee. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlackCappedChickadeeSoundRarity", 5, 2, 100);
        birdMourningDoveSoundRarity = builder.comment("Rarity modifier for calls of the Mourning Dove. 1/n chance of playing. 0 to disable this bird's calls").define("birdMourningDoveSoundRarity", 5, 2, 100);
        birdEurasianEagleOwlSoundRarity = builder.comment("Rarity modifier for calls of the Eurasian Eagle Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdEurasianEagleOwlSoundRarity", 8, 2, 100);
        birdTawnyOwlSoundRarity = builder.comment("Rarity modifier for calls of the Tawny Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdTawnyOwlSoundRarity", 8, 2, 100);
        birdLongEaredOwlSoundRarity = builder.comment("Rarity modifier for calls of the Long Eared Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdLongEaredOwlSoundRarity", 8, 2, 100);
        birdSnowyOwlSoundRarity = builder.comment("Rarity modifier for calls of the Snowy Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdSnowyOwlSoundRarity", 8, 2, 100);
        birdCommonCuckooSoundRarity = builder.comment("Rarity modifier for calls of the Common Cuckoo. 1/n chance of playing. 0 to disable this bird's calls").define("birdCommonCuckooSoundRarity", 5, 2, 100);
        birdBlackAndWhiteCasquedHornbillSoundRarity = builder.comment("Rarity modifier for calls of the Black and White Casqued Hornbill. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlackAndWhiteCasquedHornbillSoundRarity", 5, 2, 100);
        birdGreenBackedCamaropteraSoundRarity = builder.comment("Rarity modifier for calls of the Green Backed Camaroptera. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreenBackedCamaropteraSoundRarity", 5, 2, 100);
        birdSpottedDoveSoundRarity = builder.comment("Rarity modifier for calls of the Spotted Dove. 1/n chance of playing. 0 to disable this bird's calls").define("birdSpottedDoveSoundRarity", 5, 2, 100);
        birdOrientalBayOwlSoundRarity = builder.comment("Rarity modifier for calls of the Oriental Bay Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdOrientalBayOwlSoundRarity", 8, 2, 100);
        birdCoppersmithBarbetSoundRarity = builder.comment("Rarity modifier for calls of the Coppersmith Barbet. 1/n chance of playing. 0 to disable this bird's calls").define("birdCoppersmithBarbetSoundRarity", 5, 2, 100);
        birdLargeFrogmouthSoundRarity = builder.comment("Rarity modifier for calls of the Large Frogmouth. 1/n chance of playing. 0 to disable this bird's calls").define("birdLargeFrogmouthSoundRarity", 5, 2, 100);
        birdBoldStripedTitBabblerSoundRarity = builder.comment("Rarity modifier for calls of the Bold Striped Tit Babbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdBoldStripedTitBabblerSoundRarity", 5, 2, 100);
        birdBlueEaredBarbetSoundRarity = builder.comment("Rarity modifier for calls of the Blue Eared Barbet. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlueEaredBarbetSoundRarity", 5, 2, 100);
        birdRufousTailedTailorbirdSoundRarity = builder.comment("Rarity modifier for calls of the Rufous Tailed Tailorbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdRufousTailedTailorbirdSoundRarity", 5, 2, 100);
        birdYellowVentedBulbulSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Vented Bulbul. 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowVentedBulbulSoundRarity", 5, 2, 100);
        birdPlaintiveCuckooSoundRarity = builder.comment("Rarity modifier for calls of the Plaintive Cuckoo. 1/n chance of playing. 0 to disable this bird's calls").define("birdPlaintiveCuckooSoundRarity", 5, 2, 100);
        birdWilsonsBirdOfParadiseSoundRarity = builder.comment("Rarity modifier for calls of the Wilsons Bird of Paradise. 1/n chance of playing. 0 to disable this bird's calls").define("birdWilsonsBirdOfParadiseSoundRarity", 5, 2, 100);
        birdPalmCockatooSoundRarity = builder.comment("Rarity modifier for calls of the Palm Cockatoo. 1/n chance of playing. 0 to disable this bird's calls").define("birdPalmCockatooSoundRarity", 5, 2, 100);
        birdBlueWingedKookaburraSoundRarity = builder.comment("Rarity modifier for calls of the Blue Winged Kookaburra. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlueWingedKookaburraSoundRarity", 5, 2, 100);
        birdSuperbPittaSoundRarity = builder.comment("Rarity modifier for calls of the Superb Pitta. 1/n chance of playing. 0 to disable this bird's calls").define("birdSuperbPittaSoundRarity", 5, 2, 100);
        birdPapuanKingParrotSoundRarity = builder.comment("Rarity modifier for calls of the Papuan King Parrot. 1/n chance of playing. 0 to disable this bird's calls").define("birdPapuanKingParrotSoundRarity", 5, 2, 100);
        birdMagnificentBirdOfParadiseSoundRarity = builder.comment("Rarity modifier for calls of the Magnificent Bird of Paradise. 1/n chance of playing. 0 to disable this bird's calls").define("birdMagnificentBirdOfParadiseSoundRarity", 5, 2, 100);
        birdSulphurCrestedCockatooSoundRarity = builder.comment("Rarity modifier for calls of the Sulphur Crested Cockatoo. 1/n chance of playing. 0 to disable this bird's calls").define("birdSulphurCrestedCockatooSoundRarity", 5, 2, 100);
        birdPacificWrenSoundRarity = builder.comment("Rarity modifier for calls of the Pacific Wren. 1/n chance of playing. 0 to disable this bird's calls").define("birdPacificWrenSoundRarity", 5, 2, 100);
        birdAmericanRobinSoundRarity = builder.comment("Rarity modifier for calls of the American Robin. 1/n chance of playing. 0 to disable this bird's calls").define("birdAmericanRobinSoundRarity", 5, 2, 100);
        birdBarredOwlSoundRarity = builder.comment("Rarity modifier for calls of the Barred Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdBarredOwlSoundRarity", 5, 2, 100);
        birdDarkEyedJunkoSoundRarity = builder.comment("Rarity modifier for calls of the Dark Eyed Junko. 1/n chance of playing. 0 to disable this bird's calls").define("birdDarkEyedJunkoSoundRarity", 5, 2, 100);
        birdGreatHornedOwlSoundRarity = builder.comment("Rarity modifier for calls of the Great Horned Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatHornedOwlSoundRarity", 5, 2, 100);
        birdRaggianaBirdOfParadiseSoundRarity = builder.comment("Rarity modifier for calls of the Raggiana Bird of Paradise. 1/n chance of playing. 0 to disable this bird's calls").define("birdRaggianaBirdOfParadiseSoundRarity", 5, 2, 100);
        birdTropicalMockingbirdSoundRarity = builder.comment("Rarity modifier for calls of the Tropical Mockingbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdTropicalMockingbirdSoundRarity", 5, 2, 100);
        birdLewisWoodpeckerSoundRarity = builder.comment("Rarity modifier for calls of the Lewis Woodpecker. 1/n chance of playing. 0 to disable this bird's calls").define("birdLewisWoodpeckerSoundRarity", 5, 2, 100);
        birdYellowBackedOrioleSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Backed Oriole. 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowBackedOrioleSoundRarity", 5, 2, 100);
        birdKeelBilledToucanSoundRarity = builder.comment("Rarity modifier for calls of the Keel Billed Toucan. 1/n chance of playing. 0 to disable this bird's calls").define("birdKeelBilledToucanSoundRarity", 5, 2, 100);
        birdYellowThroatedToucanSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Throated Toucan. 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowThroatedToucanSoundRarity", 5, 2, 100);
        birdCrimsonBackedTanagerSoundRarity = builder.comment("Rarity modifier for calls of the Crimson Backed Tanager. 1/n chance of playing. 0 to disable this bird's calls").define("birdCrimsonBackedTanagerSoundRarity", 5, 2, 100);
        birdSlateColoredGrosbeakSoundRarity = builder.comment("Rarity modifier for calls of the Slate Colored Grosbeak. 1/n chance of playing. 0 to disable this bird's calls").define("birdSlateColoredGrosbeakSoundRarity", 5, 2, 100);
        birdSpectacledOwlSoundRarity = builder.comment("Rarity modifier for calls of the Spectacled Owl. 1/n chance of playing. 0 to disable this bird's calls").define("birdSpectacledOwlSoundRarity", 5, 2, 100);
        birdCollaredTrogonSoundRarity = builder.comment("Rarity modifier for calls of the Collared Trogon. 1/n chance of playing. 0 to disable this bird's calls").define("birdCollaredTrogonSoundRarity", 8, 2, 100);
        birdPaleBreastedThrushSoundRarity = builder.comment("Rarity modifier for calls of the Pale Breasted Thrush. 1/n chance of playing. 0 to disable this bird's calls").define("birdPaleBreastedThrushSoundRarity", 5, 2, 100);
        birdMountainWrenSoundRarity = builder.comment("Rarity modifier for calls of the Mountain Wren. 1/n chance of playing. 0 to disable this bird's calls").define("birdMountainWrenSoundRarity", 5, 2, 100);
        birdGreatAntshrikeSoundRarity = builder.comment("Rarity modifier for calls of the Great Antshrike. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatAntshrikeSoundRarity", 5, 2, 100);
        birdRedLoredAmazonSoundRarity = builder.comment("Rarity modifier for calls of the Red Lored Amazon. 1/n chance of playing. 0 to disable this bird's calls").define("birdRedLoredAmazonSoundRarity", 5, 2, 100);
        birdMontezumaOropendolaSoundRarity = builder.comment("Rarity modifier for calls of the Montezuma Oropendola. 1/n chance of playing. 0 to disable this bird's calls").define("birdMontezumaOropendolaSoundRarity", 5, 2, 100);
        birdNorthernCardinalSoundRarity = builder.comment("Rarity modifier for calls of the Northern Cardinal. 1/n chance of playing. 0 to disable this bird's calls").define("birdNorthernCardinalSoundRarity", 5, 2, 100);
        birdEasternWoodPeweeSoundRarity = builder.comment("Rarity modifier for calls of the Eastern Wood Pewee. 1/n chance of playing. 0 to disable this bird's calls").define("birdEasternWoodPeweeSoundRarity", 5, 2, 100);
        birdWoodThrushSoundRarity = builder.comment("Rarity modifier for calls of the Wood Thrush. 1/n chance of playing. 0 to disable this bird's calls").define("birdWoodThrushSoundRarity", 5, 2, 100);
        birdAmericanGoldfinchSoundRarity = builder.comment("Rarity modifier for calls of the American Goldfinch. 1/n chance of playing. 0 to disable this bird's calls").define("birdAmericanGoldfinchSoundRarity", 5, 2, 100);
        birdFoxSparrowSoundRarity = builder.comment("Rarity modifier for calls of the Fox Sparrow. 1/n chance of playing. 0 to disable this bird's calls").define("birdFoxSparrowSoundRarity", 5, 2, 100);
        birdGreatTitSoundRarity = builder.comment("Rarity modifier for calls of the Great Tit. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatTitSoundRarity", 5, 2, 100);
        frogMeditteraneanTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Meditteranean Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogMeditteraneanTreeFrogSoundRarity", 2, 2, 100);
        birdTwoBarredCrossbillSoundRarity = builder.comment("Rarity modifier for calls of the Two Barred Crossbill. 1/n chance of playing. 0 to disable this bird's calls").define("birdTwoBarredCrossbillSoundRarity", 5, 2, 100);
        birdVariedThrushSoundRarity = builder.comment("Rarity modifier for calls of the Varied Thrush. 1/n chance of playing. 0 to disable this bird's calls").define("birdVariedThrushSoundRarity", 5, 2, 100);
        frogChineseTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Chinese Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogChineseTreeFrogSoundRarity", 2, 2, 100);
        frogMoltrechtsGreenTreeFrogSoundRarity = builder.comment("Rarity modifier for calls of the Moltrechts Green Tree Frog. 1/n chance of playing. 0 to disable this frog's calls").define("frogMoltrechtsGreenTreeFrogSoundRarity", 3, 2, 100);
        birdBrownBulbulSoundRarity = builder.comment("Rarity modifier for calls of the Brown Bulbul. 1/n chance of playing. 0 to disable this bird's calls").define("birdBrownBulbulSoundRarity", 5, 2, 100);
        birdJapaneseBushWarblerSoundRarity = builder.comment("Rarity modifier for calls of the Japanese Bush Warbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdJapaneseBushWarblerSoundRarity", 5, 2, 100);
        birdAzureWingedMagpieSoundRarity = builder.comment("Rarity modifier for calls of the Azure Winged Magpie. 1/n chance of playing. 0 to disable this bird's calls").define("birdAzureWingedMagpieSoundRarity", 5, 2, 100);
        birdTaiwanBarbetSoundRarity = builder.comment("Rarity modifier for calls of the Taiwan Barbet. 1/n chance of playing. 0 to disable this bird's calls").define("birdTaiwanBarbetSoundRarity", 5, 2, 100);
        birdAsianKoelSoundRarity = builder.comment("Rarity modifier for calls of the Asian Koel. 1/n chance of playing. 0 to disable this bird's calls").define("birdAsianKoelSoundRarity", 5, 2, 100);
        birdBeijingBabblerSoundRarity = builder.comment("Rarity modifier for calls of the Beijing Babbler. 1/n chance of playing. 0 to disable this bird's calls").define("birdBeijingBabblerSoundRarity", 5, 2, 100);
        birdWhistlingCisticolaSoundRarity = builder.comment("Rarity modifier for calls of the Whistling Cisticola. 1/n chance of playing. 0 to disable this bird's calls").define("birdWhistlingCisticolaSoundRarity", 5, 2, 100);
        birdChalkBrowedMockingbirdSoundRarity = builder.comment("Rarity modifier for calls of the Chalk Browed Mockingbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdChalkBrowedMockingbirdSoundRarity", 5, 2, 100);
        birdLaughingKookaburraSoundRarity = builder.comment("Rarity modifier for calls of the Laughing Kookaburra. 1/n chance of playing. 0 to disable this bird's calls").define("birdLaughingKookaburraSoundRarity", 12, 2, 100);
        birdWesternNicatorSoundRarity = builder.comment("Rarity modifier for calls of the Western Nicator. 1/n chance of playing. 0 to disable this bird's calls").define("birdWesternNicatorSoundRarity", 5, 2, 100);
        birdYellowBilledTuracoSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Billed Turaco . 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowBilledTuracoSoundRarity", 5, 2, 100);
        birdTambourineDoveSoundRarity = builder.comment("Rarity modifier for calls of the Tambourine Dove. 1/n chance of playing. 0 to disable this bird's calls").define("birdTambourineDoveSoundRarity", 5, 2, 100);
        birdSuperbLyrebirdSoundRarity = builder.comment("Rarity modifier for calls of the Superb Lyrebird. 1/n chance of playing. 0 to disable this bird's calls").define("birdSuperbLyrebirdSoundRarity", 12, 2, 100);
        birdWillieWagtailSoundRarity = builder.comment("Rarity modifier for calls of the Willie Wagtail. 1/n chance of playing. 0 to disable this bird's calls").define("birdWillieWagtailSoundRarity", 5, 2, 100);
        birdGreenImperialPigeonSoundRarity = builder.comment("Rarity modifier for calls of the Green Imperial Pigeon. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreenImperialPigeonSoundRarity", 5, 2, 100); birdGlaucousWingedGullSoundRarity = builder.comment("Rarity modifier for calls of the Glaucous Winged Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdGlaucousWingedGullSoundRarity", 2, 2, 100);
        birdPigeoinGuillemotSoundRarity = builder.comment("Rarity modifier for calls of the Pigeoin Guillemot. 1/n chance of playing. 0 to disable this bird's calls").define("birdPigeoinGuillemotSoundRarity", 5, 2, 100);
        birdBonapartesGullSoundRarity = builder.comment("Rarity modifier for calls of the Bonapartes Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdBonapartesGullSoundRarity", 2, 2, 100);
        birdCommonLoonSoundRarity = builder.comment("Rarity modifier for calls of the Common Loon. 1/n chance of playing. 0 to disable this bird's calls").define("birdCommonLoonSoundRarity", 4, 2, 100);
        birdBlackOystercatcherSoundRarity = builder.comment("Rarity modifier for calls of the Black Oystercatcher. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlackOystercatcherSoundRarity", 2, 2, 100);
        birdSemipalmatedPloverSoundRarity = builder.comment("Rarity modifier for calls of the Semipalmated Plover. 1/n chance of playing. 0 to disable this bird's calls").define("birdSemipalmatedPloverSoundRarity", 4, 2, 100);
        birdShortTailedShearwaterSoundRarity = builder.comment("Rarity modifier for calls of the Short Tailed Shearwater. 1/n chance of playing. 0 to disable this bird's calls").define("birdShortTailedShearwaterSoundRarity", 5, 2, 100);
        birdSlatyBackedGullSoundRarity = builder.comment("Rarity modifier for calls of the Slaty Backed Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdSlatyBackedGullSoundRarity", 2, 2, 100);
        birdNorthernFulmarSoundRarity = builder.comment("Rarity modifier for calls of the Northern Fulmar. 1/n chance of playing. 0 to disable this bird's calls").define("birdNorthernFulmarSoundRarity", 3, 2, 100);
        birdForkTailedStormPetrelSoundRarity = builder.comment("Rarity modifier for calls of the Fork Tailed Storm Petrel. 1/n chance of playing. 0 to disable this bird's calls").define("birdForkTailedStormPetrelSoundRarity", 4, 2, 100);
        birdLaysanAlbatrossSoundRarity = builder.comment("Rarity modifier for calls of the Laysan Albatross. 1/n chance of playing. 0 to disable this bird's calls").define("birdLaysanAlbatrossSoundRarity", 5, 2, 100);
        birdBlackTailedGullSoundRarity = builder.comment("Rarity modifier for calls of the Black Tailed Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlackTailedGullSoundRarity", 2, 2, 100);
        birdPomarineJaegerSoundRarity = builder.comment("Rarity modifier for calls of the Pomarine Jaeger. 1/n chance of playing. 0 to disable this bird's calls").define("birdPomarineJaegerSoundRarity", 3, 2, 100);
        birdHarlequinDuckSoundRarity = builder.comment("Rarity modifier for calls of the Harlequin Duck. 1/n chance of playing. 0 to disable this bird's calls").define("birdHarlequinDuckSoundRarity", 2, 2, 100);
        birdGreyTailedTattlerSoundRarity = builder.comment("Rarity modifier for calls of the Grey Tailed Tattler. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreyTailedTattlerSoundRarity", 3, 2, 100);
        birdWhiteTailedTropicbirdSoundRarity = builder.comment("Rarity modifier for calls of the White Tailed Tropicbird. 1/n chance of playing. 0 to disable this bird's calls").define("birdWhiteTailedTropicbirdSoundRarity", 3, 2, 100);
        birdRedFootedBoobySoundRarity = builder.comment("Rarity modifier for calls of the Red Footed Booby. 1/n chance of playing. 0 to disable this bird's calls").define("birdRedFootedBoobySoundRarity", 3, 2, 100);
        birdWedgeTailedShearwaterSoundRarity = builder.comment("Rarity modifier for calls of the Wedge Tailed Shearwater. 1/n chance of playing. 0 to disable this bird's calls").define("birdWedgeTailedShearwaterSoundRarity", 2, 2, 100);
        birdGreatFrigatebirdSoundRarity = builder.comment("Rarity modifier for calls of the Great Frigatebird. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatFrigatebirdSoundRarity", 2, 2, 100);
        birdWesternOspreySoundRarity = builder.comment("Rarity modifier for calls of the Western Osprey. 1/n chance of playing. 0 to disable this bird's calls").define("birdWesternOspreySoundRarity", 4, 2, 100);
        birdGreatBlackBackedGullSoundRarity = builder.comment("Rarity modifier for calls of the Great Black Backed Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdGreatBlackBackedGullSoundRarity", 2, 2, 100);
        birdBlackBilledKittiwakeSoundRarity = builder.comment("Rarity modifier for calls of the Black Billed Kittiwake. 1/n chance of playing. 0 to disable this bird's calls").define("birdBlackBilledKittiwakeSoundRarity", 3, 2, 100);
        birdYellowLeggedGullSoundRarity = builder.comment("Rarity modifier for calls of the Yellow Legged Gull. 1/n chance of playing. 0 to disable this bird's calls").define("birdYellowLeggedGullSoundRarity", 2, 2, 100);
        builder.pop();
    }
}
