package com.therighthon.cacophony.common;

import com.therighthon.cacophony.Cacophony;
import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.dries007.tfc.util.registry.RegistryHolder;


public final class Sounds
{
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(Registries.SOUND_EVENT, Cacophony.MOD_ID);

    // Animals
    public static final Id REDWINGED_BLACKBIRD = register("ambient.bird.redwinged_blackbird");
    public static final Id PACIFIC_TREE_FROG = register("ambient.frog.pacific_tree_frog");
    public static final Id SPADEFOOT_TOAD = register("ambient.frog.spadefoot_toad");
    public static final Id SAHARA_FROG = register("ambient.frog.sahara_frog");
    public static final Id STRIPED_ROCKET_FROG = register("ambient.frog.striped_rocket_frog");
    public static final Id BRAZILIAN_TORRENT_FROG = register("ambient.frog.brazilian_torrent_frog");
    public static final Id PURPLE_FROG = register("ambient.frog.purple_frog");
    public static final Id MARSH_FROG = register("ambient.frog.marsh_frog");
    public static final Id BANDED_BULLFROG = register("ambient.frog.banded_bullfrog");
    public static final Id CENTRAL_COAST_STUBFOOT_TOAD = register("ambient.frog.central_coast_stubfoot_toad");
    public static final Id NORTHERN_CRICKET_FROG = register("ambient.frog.northern_cricket_frog");
    public static final Id ANKARAFA_SKELETON_FROG = register("ambient.frog.ankarafa_skeleton_frog");
    public static final Id PALAU_FROG = register("ambient.frog.palau_frog");
    public static final Id EDIBLE_FROG = register("ambient.frog.edible_frog");
    public static final Id MOTORBIKE_FROG = register("ambient.frog.motorbike_frog");
    public static final Id EUROPEAN_TREE_FROG = register("ambient.frog.european_tree_frog");
    public static final Id BOREAL_DIGGING_FROG = register("ambient.frog.boreal_digging_frog");
    public static final Id DYBOWSKIS_FROG = register("ambient.frog.dybowskis_frog");
    public static final Id WOOD_FROG = register("ambient.frog.wood_frog");
    public static final Id TALYSH_TOAD = register("ambient.frog.talysh_toad");
    public static final Id OLIVE_TOAD = register("ambient.frog.olive_toad");
    public static final Id CENTRAL_ASIAN_TOAD = register("ambient.frog.central_asian_toad");
    public static final Id SPECTACLED_TOAD = register("ambient.frog.spectacled_toad");
    public static final Id HAINAN_TOAD = register("ambient.frog.hainan_toad");
    public static final Id TENGCHONG_LEAF_LITTER_TOAD = register("ambient.frog.tengchong_leaf_litter_toad");
    public static final Id PAINTED_CHORUS_FROG = register("ambient.frog.painted_chorus_frog");
    public static final Id DARK_SPOTTED_FROG = register("ambient.frog.dark_spotted_frog");
    public static final Id FIRE_BELLIED_TOAD = register("ambient.frog.fire_bellied_toad");
    public static final Id CASCADES_FROG = register("ambient.frog.cascades_frog");
    public static final Id CANE_TOAD = register("ambient.frog.cane_toad");
    public static final Id STRIOLATED_BUNTING = register("ambient.bird.striolated_bunting");
    public static final Id MARSH_WREN = register("ambient.bird.marsh_wren");
    public static final Id PALLAS_GRASSHOPPER_WARBLER = register("ambient.bird.pallas_grasshopper_warbler");
    public static final Id COLLARED_KINGFISHER = register("ambient.bird.collared_kingfisher");
    public static final Id SPOTTED_TOWHEE = register("ambient.bird.spotted_towhee");
    public static final Id COMMON_LOON = register("ambient.bird.common_loon");
    public static final Id SPRING_PEEPER = register("ambient.frog.spring_peeper");
    public static final Id BOREAL_CHORUS_FROG = register("ambient.frog.boreal_chorus_frog");
    public static final Id CANADA_WARBLER = register("ambient.bird.canada_warbler");
    public static final Id ORIENTAL_REED_WARBLER = register("ambient.bird.oriental_reed_warbler");
    public static final Id ORIENTAL_SKYLARK = register("ambient.bird.oriental_skylark");
    public static final Id DJA_RIVER_SCRUB_WARBLER = register("ambient.bird.dja_river_scrub_warbler");
    public static final Id BANDED_BANANA_FROG = register("ambient.frog.banded_banana_frog");
    public static final Id LOUISIANA_WATERTHRUSH = register("ambient.bird.louisiana_waterthrush");
    public static final Id SCRUB_BLACKBIRD = register("ambient.bird.scrub_blackbird");
    public static final Id NORTHERN_WATERTHRUSH = register("ambient.bird.northern_waterthrush");
    public static final Id WESTERN_MEADOWLARK = register("ambient.bird.western_meadowlark");
    public static final Id TWO_COLORED_OVAL_FROG = register("ambient.frog.two_colored_oval_frog");
    public static final Id SLENDER_HEATH_KATYDID = register("ambient.cricket.slender_heath_katydid");
    public static final Id MEDITERRANEAN_KATYDID = register("ambient.cricket.mediterranean_katydid");
    public static final Id BLACK_LEGGED_MEADOW_KATYDID = register("ambient.cricket.black_legged_meadow_katydid");
    public static final Id SPOTTED_MEADOW_KATYDID = register("ambient.cricket.spotted_meadow_katydid");
    public static final Id EURASIAN_MEADOW_KATYDID = register("ambient.cricket.eurasian_meadow_katydid");
    public static final Id STRAIGHT_LANCED_KATYDID = register("ambient.cricket.straight_lanced_katydid");
    public static final Id AFRICAN_MEADOW_KATYDID = register("ambient.cricket.african_meadow_katydid");
    public static final Id DRUMMING_KATYDID = register("ambient.cricket.drumming_katydid");
    public static final Id BROAD_WINGED_BUSH_KATYDID = register("ambient.cricket.broad_winged_bush_katydid");
    public static final Id CARIBBEAN_MEADOW_KATYDID = register("ambient.cricket.caribbean_meadow_katydid");
    public static final Id LEAF_LADYBIRD_CRICKET = register("ambient.cricket.leaf_ladybird_cricket");
    public static final Id TWO_SPOTTED_CLICKET = register("ambient.cricket.two_spotted_clicket");
    public static final Id STEPPE_CRICKET = register("ambient.cricket.steppe_cricket");
    public static final Id MONGOLIAN_CRICKET = register("ambient.cricket.mongolian_cricket");
    public static final Id COMMON_GREEN_GRASSHOPPER = register("ambient.cricket.common_green_grasshopper");
    public static final Id INDOMALAYAN_FIELD_CRICKET = register("ambient.cricket.indomalayan_field_cricket");
    public static final Id SUMATRAN_BROWN_CRICKET = register("ambient.cricket.sumatran_brown_cricket");
    public static final Id FIELD_CRICKET = register("ambient.cricket.field_cricket");
    public static final Id OCEANIC_FIELD_CRICKET = register("ambient.cricket.oceanic_field_cricket");
    public static final Id BROWN_SPOTTED_BUSH_CRICKET = register("ambient.cricket.brown_spotted_bush_cricket");
    public static final Id BRONZY_SUNBIRD = register("ambient.bird.bronzy_sunbird");
    public static final Id STREAKY_SEEDEATER = register("ambient.bird.streaky_seedeater");
    public static final Id GRACEFUL_PRINIA = register("ambient.bird.graceful_prinia");
    public static final Id GREATER_WHITETHROAT = register("ambient.bird.greater_whitethroat");
    public static final Id COMMON_MYNA = register("ambient.bird.common_myna");
    public static final Id ASIAN_DESERT_WARBLER = register("ambient.bird.asian_desert_warbler");
    public static final Id WHITE_WINGED_SNOWFINCH = register("ambient.bird.white_winged_snowfinch");
    public static final Id ASIAN_SHORT_TOED_LARK = register("ambient.bird.asian_short_toed_lark");
    public static final Id PERUVIAN_MEADOWLARK = register("ambient.bird.peruvian_meadowlark");
    public static final Id MEADOW_BUNTING = register("ambient.bird.meadow_bunting");
    public static final Id LONG_TAILED_MEADOWLARK = register("ambient.bird.long_tailed_meadowlark");
    public static final Id PATAGONIAN_SIERRA_FINCH = register("ambient.bird.patagonian_sierra_finch");
    public static final Id NORTHERN_CARMINE_BEE_EATER = register("ambient.bird.northern_carmine_bee_eater");
    public static final Id AFRICAN_PARADISE_FLYCATCHER = register("ambient.bird.african_paradise_flycatcher");
    public static final Id EASTERN_MEADOWLARK = register("ambient.bird.eastern_meadowlark");
    public static final Id BARN_SWALLOW = register("ambient.bird.barn_swallow");
    public static final Id YELLOW_HEADED_BLACKBIRD = register("ambient.bird.yellow_headed_blackbird");
    public static final Id SONG_SPARROW = register("ambient.bird.song_sparrow");
    public static final Id RUFOUS_COLLARED_SPARROW = register("ambient.bird.rufous_collared_sparrow");
    public static final Id COMMON_STARLING = register("ambient.bird.common_starling");
    public static final Id SNOW_BUNTING = register("ambient.bird.snow_bunting");
    public static final Id RAVEN = register("ambient.bird.raven");
    public static final Id RESPLENDENT_QUETZAL = register("ambient.bird.resplendent_quetzal");
    public static final Id RAINFOREST_ROCKET_FROG = register("ambient.frog.rainforest_rocket_frog");
    public static final Id STRAWBERRY_POISON_FROG = register("ambient.frog.strawberry_poison_frog");
    public static final Id HIMALAYA_FOAM_NEST_FROG = register("ambient.frog.himalaya_foam_nest_frog");
    public static final Id WHITE_CHEEKED_BARBET = register("ambient.bird.white_cheeked_barbet");
    public static final Id MALABAR_GLIDING_FROG = register("ambient.frog.malabar_gliding_frog");
    public static final Id STUMPFFIA_MEGSONI = register("ambient.frog.stumpffia_megsoni");
    public static final Id COPES_GRAY_TREE_FROG = register("ambient.frog.copes_gray_tree_frog");
    public static final Id BRILLIANT_THIGHED_POISON_FROG = register("ambient.frog.brilliant_thighed_poison_frog");
    public static final Id STEPHENS_ROCKET_FROG = register("ambient.frog.stephens_rocket_frog");
    public static final Id HOLTS_ROBBER_FROG = register("ambient.frog.holts_robber_frog");
    public static final Id AMAZON_TOAD = register("ambient.frog.amazon_toad");
    public static final Id PEBAS_STUBFOOT_TOAD = register("ambient.frog.pebas_stubfoot_toad");
    public static final Id GRANULAR_TOAD = register("ambient.frog.granular_toad");
    public static final Id BLACKSMITH_FROG = register("ambient.frog.blacksmith_frog");
    public static final Id GREAT_KISKADEE = register("ambient.bird.great_kiskadee");
    public static final Id THRUSH_NIGHTINGALE = register("ambient.bird.thrush_nightingale");
    public static final Id BLACK_CAPPED_CHICKADEE = register("ambient.bird.black_capped_chickadee");
    public static final Id MOURNING_DOVE = register("ambient.bird.mourning_dove");
    public static final Id EURASIAN_EAGLE_OWL = register("ambient.bird.eurasian_eagle_owl");
    public static final Id TAWNY_OWL = register("ambient.bird.tawny_owl");
    public static final Id LONG_EARED_OWL = register("ambient.bird.long_eared_owl");
    public static final Id SNOWY_OWL = register("ambient.bird.snowy_owl");
    public static final Id COMMON_CUCKOO = register("ambient.bird.common_cuckoo");
    public static final Id BLACK_AND_WHITE_CASQUED_HORNBILL = register("ambient.bird.black_and_white_casqued_hornbill");
    public static final Id GREEN_BACKED_CAMAROPTERA = register("ambient.bird.green_backed_camaroptera");
    public static final Id SPOTTED_DOVE = register("ambient.bird.spotted_dove");
    public static final Id ORIENTAL_BAY_OWL = register("ambient.bird.oriental_bay_owl");
    public static final Id COPPERSMITH_BARBET = register("ambient.bird.coppersmith_barbet");
    public static final Id LARGE_FROGMOUTH = register("ambient.bird.large_frogmouth");
    public static final Id BOLD_STRIPED_TIT_BABBLER = register("ambient.bird.bold_striped_tit_babbler");
    public static final Id BLUE_EARED_BARBET = register("ambient.bird.blue_eared_barbet");
    public static final Id RUFOUS_TAILED_TAILORBIRD = register("ambient.bird.rufous_tailed_tailorbird");
    public static final Id YELLOW_VENTED_BULBUL = register("ambient.bird.yellow_vented_bulbul");
    public static final Id PLAINTIVE_CUCKOO = register("ambient.bird.plaintive_cuckoo");
    public static final Id WILSONS_BIRD_OF_PARADISE = register("ambient.bird.wilsons_bird_of_paradise");
    public static final Id PALM_COCKATOO = register("ambient.bird.palm_cockatoo");
    public static final Id BLUE_WINGED_KOOKABURRA = register("ambient.bird.blue_winged_kookaburra");
    public static final Id SUPERB_PITTA = register("ambient.bird.superb_pitta");
    public static final Id PAPUAN_KING_PARROT = register("ambient.bird.papuan_king_parrot");
    public static final Id MAGNIFICENT_BIRD_OF_PARADISE = register("ambient.bird.magnificent_bird_of_paradise");
    public static final Id SULPHUR_CRESTED_COCKATOO = register("ambient.bird.sulphur_crested_cockatoo");
    public static final Id PACIFIC_WREN = register("ambient.bird.pacific_wren");
    public static final Id AMERICAN_ROBIN = register("ambient.bird.american_robin");
    public static final Id BARRED_OWL = register("ambient.bird.barred_owl");
    public static final Id DARK_EYED_JUNKO = register("ambient.bird.dark_eyed_junko");
    public static final Id GREAT_HORNED_OWL = register("ambient.bird.great_horned_owl");
    public static final Id RAGGIANA_BIRD_OF_PARADISE = register("ambient.bird.raggiana_bird_of_paradise");
    public static final Id TROPICAL_MOCKINGBIRD = register("ambient.bird.tropical_mockingbird");
    public static final Id LEWIS_WOODPECKER = register("ambient.bird.lewis_woodpecker");
    public static final Id YELLOW_BACKED_ORIOLE = register("ambient.bird.yellow_backed_oriole");
    public static final Id KEEL_BILLED_TOUCAN = register("ambient.bird.keel_billed_toucan");
    public static final Id YELLOW_THROATED_TOUCAN = register("ambient.bird.yellow_throated_toucan");
    public static final Id CRIMSON_BACKED_TANAGER = register("ambient.bird.crimson_backed_tanager");
    public static final Id SLATE_COLORED_GROSBEAK = register("ambient.bird.slate_colored_grosbeak");
    public static final Id SPECTACLED_OWL = register("ambient.bird.spectacled_owl");
    public static final Id COLLARED_TROGON = register("ambient.bird.collared_trogon");
    public static final Id PALE_BREASTED_THRUSH = register("ambient.bird.pale_breasted_thrush");
    public static final Id MOUNTAIN_WREN = register("ambient.bird.mountain_wren");
    public static final Id GREAT_ANTSHRIKE = register("ambient.bird.great_antshrike");
    public static final Id RED_LORED_AMAZON = register("ambient.bird.red_lored_amazon");
    public static final Id MONTEZUMA_OROPENDOLA = register("ambient.bird.montezuma_oropendola");
    public static final Id NORTHERN_CARDINAL = register("ambient.bird.northern_cardinal");
    public static final Id EASTERN_WOOD_PEWEE = register("ambient.bird.eastern_wood_pewee");
    public static final Id WOOD_THRUSH = register("ambient.bird.wood_thrush");
    public static final Id AMERICAN_GOLDFINCH = register("ambient.bird.american_goldfinch");
    public static final Id FOX_SPARROW = register("ambient.bird.fox_sparrow");
    public static final Id GREAT_TIT = register("ambient.bird.great_tit");
    public static final Id MEDITTERANEAN_TREE_FROG = register("ambient.frog.meditteranean_tree_frog");
    public static final Id TWO_BARRED_CROSSBILL = register("ambient.bird.two_barred_crossbill");
    public static final Id VARIED_THRUSH = register("ambient.bird.varied_thrush");
    public static final Id CHINESE_TREE_FROG = register("ambient.frog.chinese_tree_frog");
    public static final Id MOLTRECHTS_GREEN_TREE_FROG = register("ambient.frog.moltrechts_green_tree_frog");
    public static final Id BROWN_BULBUL = register("ambient.bird.brown_bulbul");
    public static final Id JAPANESE_BUSH_WARBLER = register("ambient.bird.japanese_bush_warbler");
    public static final Id AZURE_WINGED_MAGPIE = register("ambient.bird.azure_winged_magpie");
    public static final Id TAIWAN_BARBET = register("ambient.bird.taiwan_barbet");
    public static final Id ASIAN_KOEL = register("ambient.bird.asian_koel");
    public static final Id BEIJING_BABBLER = register("ambient.bird.beijing_babbler");
    public static final Id WHISTLING_CISTICOLA = register("ambient.bird.whistling_cisticola");
    public static final Id CHALK_BROWED_MOCKINGBIRD = register("ambient.bird.chalk_browed_mockingbird");
    public static final Id LAUGHING_KOOKABURRA = register("ambient.bird.laughing_kookaburra");
    public static final Id WESTERN_NICATOR = register("ambient.bird.western_nicator");
    public static final Id YELLOW_BILLED_TURACO_ = register("ambient.bird.yellow_billed_turaco_");
    public static final Id TAMBOURINE_DOVE = register("ambient.bird.tambourine_dove");
    public static final Id SUPERB_LYREBIRD = register("ambient.bird.superb_lyrebird");
    public static final Id WILLIE_WAGTAIL = register("ambient.bird.willie_wagtail");
    public static final Id GREEN_IMPERIAL_PIGEON = register("ambient.bird.green_imperial_pigeon");
    public static final Id LEAVES_IN_WIND = register("ambient.wind.leaves_in_wind");
    public static final Id LEAVES_IN_WIND_STRONG = register("ambient.wind.leaves_in_wind_strong");
    public static final Id WIND_IN_GRASS = register("ambient.wind.wind_in_grass");
    public static final Id WIND_IN_GRASS_STRONG = register("ambient.wind.wind_in_grass_strong");
    public static final Id ICE_CREAK = register("ambient.ice.ice_creak");
    public static final Id WIND_LOOP = register("ambient.wind.wind_loop");


    private static Id register(String name)
    {
        return new Id(SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(CacophonyHelpers.identifier(name))));
    }

    public record Id(DeferredHolder<SoundEvent, SoundEvent> holder) implements RegistryHolder<SoundEvent, SoundEvent> {}
}
